image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Couchbase
    command: ./startcb.sh
  - name: Log use
    command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=golang-quickstart-repo&source=gitpod' > /dev/null
  - name: Start app
    command: cd github.com/couchbase-examples/golang-quickstart && go run .

# exposed ports
ports:
  - port: 5000
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
  - port: 8091
    onOpen: open-browser
  - port: 8092-22000
    onOpen: ignore
  - port: 4369
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true

vscode:
  extensions:
    - golang.Go