name: Go Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        run: |
          sudo apt -y update
          sudo apt -y install golang
          export PATH=$PATH:/usr/local/go/bin
      - name: Setup golang app
        run: |
          go run . &
          sleep 10
      - name: Run Go Tests
        run: |
          cd test 
          go test ./...
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure,warnings"
          notification_title: "Repo: *{repo}*"
          message_format: "{emoji}    *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: "<{run_url}|View Full Run on GitHub>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

